### ISSUE TITLE
1776: "F" key disabled - cannot switch to third or first-person view

### ISSUE THREAD

**Issue by tedbarnett** [TimeWalkOrg/Manhattan#148] opened 2024-10-12 19:18 UTC
Seems to work fine in 1664, but not 1776.  "F" key does nothing: stay in "fly" mode.

**Comment by deedox** [comment] 2024-10-13 11:01
Please pull my latest branch, the issue is not appearing there.. I've also merged everything with the latest main..

**Comment by tedbarnett** [comment] 2024-10-13 15:53
Also and perhaps related: if I switch to First Person mode while in 1664, then T and choose 1776, my character is stuck in the ground as below:

![Image](https://github.com/user-attachments/assets/23a1f011-6902-4a87-a094-f4115af79dac)

**Comment by tedbarnett** [comment] 2024-10-13 15:57
It does look like "F" works in 1776 (if I start there first), but if I change levels ("T", etc.) and am walking around, weird things happen.  Like this:

![Image](https://github.com/user-attachments/assets/2e784851-73d6-4eb7-a2b0-d6e79ea58145)

**Comment by deedox** [comment] 2024-10-13 16:20
Yeah that's because the unloaded level losses it's collision before the new one is loaded and a new collision is enabled again.. 
So if you stand on the ground when timetravel the character will drop.. There are multiple solutions to this, will check if I can keep the old collision until the new one is loaded.

**Closed as completed** 2024-11-09 19:45 UTC
